### ISSUE TITLE
Add Automatic-Module-Name clause to jar manifest

### ISSUE THREAD

**Issue by bjorndarri** [msteiger/jxmapviewer2#101]
Hi,

Would you consider adding an Automatic-Module-Name clause to the jar manifest?

```groovy
jar {
    manifest {
        attributes('Automatic-Module-Name': 'org.jxmapviewer.jxmapviewer2')
    }
}
```
Thanks.

**Comment by msteiger** [comment]
Yes, sounds good. Need to brush up my knowledge about new Java features first a bit. Will review asap.

**Comment by msteiger** [comment]
From what I understood now, this should be automatically created when importing the jar in a Java9+ project. Maybe we should instead aim for a explicit module definition through a `module-info.java` file. What do you think?

**Comment by bjorndarri** [comment]
I'm all for proper modularization, but the problem is with Java 8 compatibility, which will be broken if you upgrade to Java 9 and add a module-info.java file, although there are ways to mitigate that with [multi-release-jar files](https://www.baeldung.com/java-multi-release-jar), but I haven't experimented with that personally.

This way of adding 'Automatic-Module-Name' to the manifest is the simplest way to allow usage in both Java 8 and modularized Java >=9 applications.

I'm using jxmapviewer2 in an application that has both Java 8 and Java 11 versions, so this solution still gets my vote :).

**Comment by msteiger** [comment]
Okay, sounds reasonable. Thanks. Isn't the `Automatic-Module-Name` generated by default if you include a jar file without that attribute? Will experiment a bit with it asap and merge your PR then.

**Comment by bjorndarri** [comment]
Without the manifest attribute a module name is derived from the jar file name, which is basically an unstable fallback mechanism and quite inconvenient to work with.

See for example: [Automatic-Module-Name: Calling all Java Library Maintainers](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)
and [Explicitly Naming Automatic Java Modules](https://dzone.com/articles/explicitly-naming-automatic-java-modules).

**Comment by msteiger** [comment]
Makes sense, thanks for your patience!
