### ISSUE TITLE
Can we load shape files on top of the map for jxmapviewer2?

### ISSUE THREAD

**Issue by TamjidTayeb** [msteiger/jxmapviewer2#107]
Can we load shape files on top of the map for jxmapviewer2?

**Comment by msteiger** [comment]
Yes, you can create your own OverlayRenderer if you like. What kind of shapes do you want to show?

**Comment by TamjidTayeb** [comment]
I want to use this shape file:
[Uploading ipa_dedicated_public.zip…](zip of .shp file i want to render on top of the map)

I wasn't able to find any examples of rendering shape files on the github? Would it be possible to see one? Thanks for the quick response

**Comment by msteiger** [comment]
Sorry for the delay, it should be possible to render it as an overlay, yes. There are a few examples in the project on how to render on top of the map. To convert the Shape file into something that Swing can render, you need to parse it. Maybe you can find something useful here: https://stackoverflow.com/questions/2044876/does-anyone-know-of-a-library-in-java-that-can-parse-esri-shapefiles
