### ISSUE TITLE
Is it possible to update routes?

### ISSUE THREAD

**Issue by TamjidTayeb** [msteiger/jxmapviewer2#112]
Is it possible to update routes?

I am trying to follow this example:
https://github.com/msteiger/jxmapviewer2/tree/master/examples/src/sample2_waypoints
But I would like my users to be able to view different routes, is it possible to refactor the RoutePainter class to update the track? I tried updating the track but the new track is not rendered.

Thanks

**Comment by msteiger** [comment]
Sorry for the delay! Yes, you can copy and paste the RoutePainter into your own application and change it as you wish.
You can update the track, but need to trigger a repaint() to make your changes visible.

**Comment by maeichris** [comment]
It looks like this issue (a question) has been dealt with (answered satisfactorily).  Can this issue be closed now?

**Comment by msteiger** [comment]
Thanks for the reminder
