### ISSUE TITLE
JavaFX compatibility

### ISSUE THREAD

**Issue by BaherW** [msteiger/jxmapviewer2#118]
Importing through Gradle while using JavaFX doesn't work.

Error occurred during initialization of boot layer
java.lang.module.FindException: Module jxmapviewer2 not found, required by Software_Design_Assignments

**Comment by msteiger** [comment]
I don't know your setup, but I don't think that it's related to JavaFX. You need to include jxmapviewer2 as a classpath dependency or wrapped as an "automatic module".

Alternatively, we could package it properly by adding a `module-info.java`, but I haven't looked into it yet.

**Comment by msteiger** [comment]
This issue should be fixed in jxmapviewer 2.8 now.
