### ISSUE TITLE
AbstractTileFactory#tileMap causing OutOfMemory after long usage

### ISSUE THREAD

**Issue by MaxKoenig94** [msteiger/jxmapviewer2#119]
Hi,
first of all, thanks for the great library.

But, when using the library to display large maps (e.g. europe), the TileCache is cleared and limited in its size, but the tileMap is still storing all the Tiles and therefore causing OutOfMemory if used for longer time. 

Wouldn't it be wise, to provide possibilities to clear the map or limit its size?

**Comment by msteiger** [comment]
Thanks for the hint! Yes, it sounds very reasonable to limit the number of tiles. Do you think you can have a look at the code and provide a fix? I will review it then.

**Comment by MaxKoenig94** [comment]
I just created a pull request for the mentioned fix. Feel free to ask me any questions that come to your mind.

**Comment by msteiger** [comment]
Great, thanks a lot! Will review as soon as I can .. hopefully this weekend!
