### ISSUE TITLE
OOM and cache

### ISSUE THREAD

**Issue by mikey75** [msteiger/jxmapviewer2#128]
https://github.com/msteiger/jxmapviewer2/blob/8e162823d1bbbfeab4d7487a2fd4f43a100643ec/jxmapviewer2/src/main/java/org/jxmapviewer/viewer/AbstractTileFactory.java#L411

This is soo wrong. Why wait until cache eats all memory and then do cache.clear() sacrificing all cache entries? 
Why not make the cache LRU cache, with settable upper limit, which if reached, causes only the least recently used tiles to be removed from cache.

**Comment by mikey75** [comment]
Ah, sorry, there is an LRU tile cache :) This software has so much hidden under the hood :) Very robust!

    private LinkedHashMap<String, Tile> tileMap = new LinkedHashMap<String, Tile>() {
            private static final int CACHE_SIZE = 512;
            private static final long serialVersionUID = 1;

            @Override
            protected boolean removeEldestEntry(final Map.Entry<String, Tile> eldest) {
                return size() > CACHE_SIZE;
            }
        };

**Comment by msteiger** [comment]
I think that you are right, the OOME should not be handled. This code was written a very long time ago, maybe it made sense back then.
