### ISSUE TITLE
Help Needed: Using MouseEvents to create new GeoPoint

### ISSUE THREAD

**Issue by andyrozman** [msteiger/jxmapviewer2#132]
Hi !
I am trying to add new "Waypoints" and I am having little bit of problem with it... Sorry to open ticket for this, but there are no Discussions enabled on this project, and I am little bit stuck.

So I have added MouseListener and I would like to create a waypoint on the area I click on (so theoretically I need Geo location of clicked point).

It might be nice to enable Discussions or maybe some usage Wiki (examples are ok, but they don't cover every situation).

This is great viewer and has nice features...

Andy

**Comment by andyrozman** [comment]
Doesn't help... I looked at this already...

We would need to translate location on window into Graphics2D location (of the tile) and if we had that then we could use current metod pixelToGeo(). So for example item on Graphics2D has very big location (x=16195217,y=10886860 this is near of the item where I am trying to put it down to) and at the moment I am not sure how I can translate mouse location into "Tile Location"... 
I also wrote new renderer and I wanted to make icon (I paint icons for specific location) clickable, which would also require similar method... I don't know your application enough (and Graphics2D either) to know which way to look, or if what I am asking is even possible, but if I wanted to have interactive adding of new items, that is something that would be needed. But maybe this project was not meant for that... Do you have alternative I could use, that would allow interactive adding of new items? This is main reason I need your application and why I took it as basis for what I am doing?

**Comment by andyrozman** [comment]
Actually I was able to find solution... Maybe you could add method to viewer so that others could use it. Something like this:

Parameters you have to pass would be : this.mouseEvent.getX(), this.mouseEvent.getY()

public Point translateMouseLocationToViewportPixel(int mouseX, int mouseY) {
        Rectangle rectangle = mapViewer.getViewportBounds();

        int pos_x = rectangle.x + mouseX;
        int pos_y = rectangle.y + mouseY;

        Point newPoint = new Point(pos_x, pos_y);

        System.out.println("Position on Viewport: " + newPoint);

        return newPoint;
    }

    public GeoPosition translateMouseLocationToGeoPosition(int mouseX, int mouseY) {
        Point point = translateMouseLocationToViewportPixel(mouseX, mouseY);
        GeoPosition geoPosition = mapViewer.getTileFactory().pixelToGeo(point, mapViewer.getZoom());

        System.out.println("GeoPosition: " + geoPosition);
        
        return geoPosition;
    }

P.S.: Consider enabling discussions for the project...

**Comment by msteiger** [comment]
Thanks, I will create a small example and have a look at the "Discussions" option here in Github.

**Comment by msteiger** [comment]
The option "General Discussions" is available now.
