### ISSUE TITLE
Newest release does not support Java Modules

### ISSUE THREAD

**Issue by notfirefox** [msteiger/jxmapviewer2#133]
I am currently evaluating the use of this component and I have come 
to find out that the newest release on maven does not properly support Java 9+ Modules.

This seems to be fixed, however by #102. The change has been merged into `master` in December 2020, but the newest release on maven, which is version `2.6`, is from October 2020. Therefore a new release would be appreciated.

**Comment by msteiger** [comment]
Good point, thanks - I will create a new release until end of the year (hopefully).

**Comment by msteiger** [comment]
Hello, I released version 2.8 and it is now available at Maven Central:

https://mvnrepository.com/artifact/org.jxmapviewer/jxmapviewer2

Can you please check if your issue is solved?

**Comment by ghost** [comment]
Can confirm that this issue is solved. Thank you!
