### ISSUE TITLE
Tile cache doesn't work if the URLs vary

### ISSUE THREAD

**Issue by Danstahr** [msteiger/jxmapviewer2#29]
Currently, the Tile Cache is based on the URL of the image inside. This doesn't work well for cases where the URL can vary, for example if there are multiple instances of the server and the URLs are distributed randomly between them (like `s1.maps.example.com` and `s2.maps.example.com`). 

This can be handled in the Factory Info (so that it always returns something like `(x + y) % number_of_servers`), but I think the cache shouldn't rely on uniqueness of the URLs and instead should be based on the `X`, `Y`, `zoom` and `mapId` fields.

**Comment by msteiger** [comment]
Yay! Took me only 3,5 years to fix this issue.
