### ISSUE TITLE
geoposition serializable

### ISSUE THREAD

**Issue by flashpixx** [msteiger/jxmapviewer2#30]
Hello,

can you implement the Serializable interface to the GeoPosition class, so the position can be stored / read from a file?

Thx

**Comment by msteiger** [comment]
That would be possible, yes. However, I strongly suggest using a proper serialization framework. Java's internal serialization is not meant to store data on a file. It was created for network communication.

[Google's gson](https://code.google.com/p/google-gson/) and [Jackson](http://jackson.codehaus.org/) are both excellent tools to read/write JSON. This is also human-readable.

Does that help?

**Comment by flashpixx** [comment]
I need both structures, for file stream I'm using Gson but on network I would like to use the Serializable interface. For network communication I have create a derived class of your Geoposition class with a transient member, but it is a redundant structure

**Comment by msteiger** [comment]
I see - I don't have the workspace here atm, but I can have a look next week. If you want to can send a Pull Request with the change. One viable alternative is also [Google's protocol buffers](https://github.com/google/protobuf/), but I understand that it could be too complex for something simple like that.

**Comment by flashpixx** [comment]
This feature request is not urgent, so it can be added in the next release. I cannot create a Pull Request, because at the moment I don't have any time

**Comment by matthiasblaesing** [comment]
This is fixed via the merge and should be closed.

**Comment by msteiger** [comment]
Right - thanks!
