### ISSUE TITLE
how to draw on all maps

### ISSUE THREAD

**Issue by robotfire** [msteiger/jxmapviewer2#33]
When I draw something on the map and zoom out really far, it's only drawn on the middle map (many maps are placed side by side so as to create a "wrapping" effect).  Is there an example that shows how to draw on all of the maps?  I'm expecting a waypoint to show up on each wrapped map.

Also, great work!  I work with a lot of people who use maps, and none of us knows about this continued work.  I'm going to push for using it in our organization.

**Comment by msteiger** [comment]
I'm not sure I understand. Do you have an example or a screenshot of the problem?

**Comment by msteiger** [comment]
Closing from lack of feedback.
