### ISSUE TITLE
Control max extent

### ISSUE THREAD

**Issue by albertotn** [msteiger/jxmapviewer2#38]
I suggest to add a new feature: control max extent.

On map init specify max extent (for zoom and pan of the map) and then check it on pan and move.

I've tried to add it and for Zoom is simple, just check maximum zoom on MouseWheelListener.
For pan I'm asking for support.

Thanks in advance

**Comment by msteiger** [comment]
Just to get it right: you are looking for ways to restrict the navigable part of the map to a certain area. Is that correct? If yes, you can have a look at [org/jxmapviewer/input/PanMouseInputListener.java](https://github.com/msteiger/jxmapviewer2/blob/master/jxmapviewer2/src/main/java/org/jxmapviewer/input/PanMouseInputListener.java).

Let me know if that helps ..

**Comment by albertotn** [comment]
It helps thanks, I wonder if this feature is on roadmap or I'm the first
