### ISSUE TITLE
Maintain tile caching after program terminated

### ISSUE THREAD

**Issue by stel78** [msteiger/jxmapviewer2#41]
Congratulation ,great job .
I would like to ask how we can maintain tile cache for a standard duration of time ?
For example three months.
For the time being using the code from the samples after program termination the cache is gone.

Thanks in advanced

**Comment by msteiger** [comment]
You might want to have a look at [LocalResponseCache](https://github.com/msteiger/jxmapviewer2/blob/master/jxmapviewer2/src/main/java/org/jxmapviewer/viewer/LocalResponseCache.java). It writes the tiles directly into a folder tree in png format. You can set the timeout to whatever value you want. Does that help?

**Comment by stel78** [comment]
Thanks it worked.
