### ISSUE TITLE
offline map

### ISSUE THREAD

**Issue by vandyroyy** [msteiger/jxmapviewer2#42]
Thank you for the good samples, i have a question, whether such maps can be created offline ?

**Comment by msteiger** [comment]
Yes, they can! You can either active the file cache so that tiles are downloaded from a map server and stored on your hard drive so you can use them later or create a new tile set from scratch. You can use a TileInfoFactory to define the folder structure / file names as you wish.

**Comment by fubian** [comment]
Do you have an example for this?
