### ISSUE TITLE
LocalResponseCache not working when PrintServiceLookup is called

### ISSUE THREAD

**Issue by Ruediger34** [msteiger/jxmapviewer2#44]
In case the java class PrintServiceLookup.lookupPrintServices from javax.print.PrintServiceLookup is called, the LocalResponseCache doesn´t create the tilecache. 
The folder is created, but tiles (.png) are not stored.

This issue occurs only on Linux (Debian).
On Windows the cache work as expected. 

Do you have any ideas?

**Comment by msteiger** [comment]
I don't see any reasonable connection between the two. That said, the LocalResponseCache installation is global and might be overriden by the PrintServiceLookup implementation.

You could add a breakpoint to find out who calls `ResponseCache.setDefault()`.

**Comment by Ruediger34** [comment]
I will give you an update to this "issue", in case anyone has the same obscurity.

If I compile the `jxmapviewer2/examples/src/sample7_swingwaypoints/Sample7.java`  with jdk8
and add at the first line in the main function:
`PrintServiceLookup.lookupDefaultPrintService();`
the cache is not working on linux-systems (Debian, Fedora) with openjdk8 and the official oraclejdk8. 
I have also added a breakpoint to `ResponseCache.setDefault()` which is only called by jxmapviewer.
If I compile the project with jdk7 and use jre7, the cache respectively the .png files are properly created.

This bevaviour only occurs on my tested linux-systems (Debian, Fedora). 
On Windows everything is fine with jdk7/8.
Finally I don´t have a solution for this, except to use jdk7.
