### ISSUE TITLE
Loading image not hidden when windows is resized

### ISSUE THREAD

**Issue by PrimosK** [msteiger/jxmapviewer2#45]
When window is resized beyond the map height, the loading images positioned above the map are not hidden. 

This can be reproduced on **[sample7_swingwaypoints](https://github.com/msteiger/jxmapviewer2/tree/master/examples/src/sample7_swingwaypoints)** example:
![image](https://cloud.githubusercontent.com/assets/1519324/16554571/1052736c-41d0-11e6-8519-916d6b77d5c5.png)

Steps to reproduce this:
- Run **[sample7_swingwaypoints](https://github.com/msteiger/jxmapviewer2/tree/master/examples/src/sample7_swingwaypoints)** example
- Zoom out
- Resize the window beyond the map height

**Comment by msteiger** [comment]
Please verify that your issue is now fixed.

**Comment by PrimosK** [comment]
I've tested it out and I can confirm that issue is gone now. Thank you for looking into this.
