### ISSUE TITLE
JavaFX version planned?

### ISSUE THREAD

**Issue by ssaring** [msteiger/jxmapviewer2#50]
Hello,

thanks for continuation of the JXMapViewer project! I use it in my JavaFX based SportsTracker project ( https://github.com/ssaring/sportstracker ) and so I have to handle with many JavaFX<->Swing integration pitfalls.
Are there any plans to create a JavaFX based version of JXMapViewer?

Bye, Stefan

**Comment by msteiger** [comment]
Well, yes and no. I'd like to do it, but there quite a bunch of items with higher priority on my TODO list.
