### ISSUE TITLE
Being able to tell when all tiles are loaded up.

### ISSUE THREAD

**Issue by JayEsEm** [msteiger/jxmapviewer2#51]
Greetings,

First of all, thank you for your development of JXMapViewer. I am currently using it on our network planification tool (https://github.com/girtel/Net2Plan) and so far, it has been of much utility. However, I have found myself with a problem I have not found a solution to.

In this project, I am using the map viewer as a way of showing a non-interactive map centered on a specific point. The thing is that I need the map to finish loading before the program continues its execution. Nevertheless, I have not found a proper way to make the program wait until the visible tiles have finished loading. Is there some way this could be achieved?.

Thank you for your time, Jorge.

**Comment by msteiger** [comment]
Sorry for the delay. Not that I know of. It should be possible to add a new event type to signal that. Is it still relevant for you?

**Comment by Ruediger34** [comment]
I am also interested in a functionality like this.
