### ISSUE TITLE
SwingLabsBlueMarble is not available anymore.

### ISSUE THREAD

**Issue by RobertZenz** [msteiger/jxmapviewer2#52]
The SwingLabsBlueMarble provider is not available anymore. From what I could gather the website is still there but the tile server is gone.

However, one might be able to fall over to [the NASA source, which is a WMS service](https://svs.gsfc.nasa.gov/2915). I tried connecting to it:

    mapKit.setTileFactory(new WMSTileFactory(new WMSService("https://svs.gsfc.nasa.gov/cgi-bin/wms?SERVICE=WMS&", "2915_21223")));

But seems like the service does not like the request it is send:

    $ curl --dump-header - "https://svs.gsfc.nasa.gov/cgi-bin/wms?SERVICE=WMS&version=1.1.1&request=GetMap&Layers=2915_21223&format=image/jpeg&BBOX=0.0,0.0,0.0054931640625,0.00549316405408165&width=500&height=500&SRS=EPSG:4326&Styles="

    HTTP/1.1 200 OK
    Date: Tue, 07 Feb 2017 15:15:32 GMT
    Server: Apache
    Strict-Transport-Security: max-age=31536000; includeSubdomains;
    Transfer-Encoding: chunked
    Content-Type: application/vnd.ogc.se_xml
    
    <?xml version='1.0' encoding="UTF-8" standalone="no" ?>
    <!DOCTYPE ServiceExceptionReport SYSTEM
     "http://svs.gsfc.nasa.gov/exception_1_1_0.dtd">
    <ServiceExceptionReport version="1.1.0">
      <ServiceException code="InvalidSize">
        WIDTH is invalid for layer. Should be 1024.
      </ServiceException>
      <ServiceException code="InvalidSize">
        HEIGHT is invalid for layer.  Should be 512.
      </ServiceException>
      <ServiceException code="InvalidFormat">
        FORMAT is invalid for layer.  Should be image/png.
      </ServiceException>
      <ServiceException code="InvalidBBOX">
        BBOX is invalid for layer.  Should be [-180,-90,180,90]
      </ServiceException>
      <ServiceException code="LayerNotDefined">
        Unable to find layer.
      </ServiceException>
    </ServiceExceptionReport>

Not sure why the layer is reported as undefined, if one does fix all the other errors it works. I'm not sure what the appropriate fix for that should be.

**Comment by RobertZenz** [comment]
On a related note, the default NASA server in the `WMSService` isn't available anymore, either.

**Comment by msteiger** [comment]
I assume that this is an issue with the WMS service, not JXMapViewer.

As the TODO comment states already, the default entry (NASA) should be removed, yes.
[WMSService.java#L27](https://github.com/msteiger/jxmapviewer2/blob/0786bc9deef3c08ccf6be9124b4275fd8224815e/jxmapviewer2/src/main/java/org/jxmapviewer/viewer/wms/WMSService.java#L27).

I think I removed the SwingLabs WMS already. Do you still see it somewhere?

**Comment by RobertZenz** [comment]
> I assume that this is an issue with the WMS service, not JXMapViewer.

To be honest, I'd need to the WMS description to comment on that. But I thought it might be something of interest to you. Is refactoring `WMSService` to be able to set all these parameters (in an extending class) of interest?

 > I think I removed the SwingLabs WMS already. Do you still see it somewhere?

Sorry, I should have made clear that I'm taking about the [the DefaultProvider in JXMapKit](https://github.com/msteiger/jxmapviewer2/blob/741032b5b10c63ba6dd490fb6be8ad7a987d2ce6/jxmapviewer2/src/main/java/org/jxmapviewer/JXMapKit.java#L76).

**Comment by msteiger** [comment]
Finally this is fixed. Thanks for the hint.
