### ISSUE TITLE
Using my own tile server

### ISSUE THREAD

**Issue by arashmidos** [msteiger/jxmapviewer2#54]
Hi,

I've just tried jxmapviewer2 and everything works fine with `http://tile.openstreetmap.org`.
Then, I asked someone to setup my own tile server and example url is as follow:

http://89.187.66.107:8090/styles/klokantech-basic/?vector#9.53/51.5515/-0.0701

I developed a new TileFactoryInfo class to match this url as follow:
```
@Override
  public String getTileUrl(int x, int y, int zoom) {
    zoom = max - zoom;
    String url = this.baseURL + "" + zoom + "/" + x + "/" + y  + "";
    return url;
  }
```

But x,y are not GeoPosition, so it's not working. 
So, How can I use jxmapviewer2 with my own tile server?

**Comment by msteiger** [comment]
Sorry, I didn't see this issue until now. I think that you will need to discretize the map coordinates and provide them as renderable square images. So it's not really an issue with jxmapviewer, as I understand it.
