### ISSUE TITLE
Routing on streets using jxmapviewer2

### ISSUE THREAD

**Issue by sagarjangid** [msteiger/jxmapviewer2#55]

**Comment by msteiger** [comment]
Please state what the exact issue is about.

**Comment by sagarjangid** [comment]
I want to display a road route from one position to another. Can I do this using jxmapviewer2 as I have loaded my own offline map and now the task is to show a road route between two waypoints.

**Comment by PrimosK** [comment]
Hi @sagarjangid,

It's possible to draw whatever you want over the map - see this example:
[RoutePainter.java](https://github.com/msteiger/jxmapviewer2/blob/master/examples/src/sample2_waypoints/RoutePainter.java
)

Using same technique you could draw the desired route from one position to another.

Side note: 
As JXMapViewer2 is just a rendering library, you will have to to provide route points by yourself. One possible option is to use [GraphHopper ](https://github.com/graphhopper/graphhopper).

In the future I suggest to post such questions to [StackOverflow ](https://stackoverflow.com/search?q=JXMapViewer2).

**Comment by sagarjangid** [comment]
Thanks for that but when I draw route using RoutePainter.java it draw a straight line between both the waypoints but I want to draw a road route that can be followed by any car.

Sorry, for posting the question here.

**Comment by msteiger** [comment]
You will need the route information then. The JXMapViewer just downloads the rendered tile images from the server, it does not know about anything in those images. The good news is that this information is available on many Web Map Services (WMS) such as OpenStreetMap.

You might want to download the raw vector graphics data from OpenStreetMap to extract routing information from it. I guess that it will take a bit of effort to achieve that, though.

**Comment by sagarjangid** [comment]
Thanks for providing information.
I have downloaded the map data now I am trying to use it with jxmapviewer2. I have loaded the data in a spatial database and now I am trying to mark a route . I don't know how to highlight that route in jxmapviewer2 map tiles.
 If you have any idea then please provide me.

**Comment by msteiger** [comment]
Please have a look on the example, @PrimosK provided above. Just draw the route with `Graphics2D` in an overlay.
