### ISSUE TITLE
A whole lot of caching

### ISSUE THREAD

**Issue by eialbur** [msteiger/jxmapviewer2#60]
Hi - thank you sooooo much for this simple-to-understand/simple-to-use library. I must have spent a solid week looking at alternatives until I found this.

I do have a question, though. I'm not trying to pick nits, but as I was reviewing the code to look for a place to handle offline maps I saw just how much caching is going on at various levels. There's the local response cache. There is the tile cache (which really seems to me to be an image cache). There is the tile map (which does seem to be a tile cache).  I have put numerous trace messages in the methods and it appears to me that the tile map does almost all of the heavy lifting .. so much so that I question the value of the added complexity of all the other caches. 

Are there usage scenarios I'm not thinking of where these other caches come into play, or are they there for historical reasons?

**Comment by msteiger** [comment]
Hey ... thank you for your kind words. Usually people just complain about things not working :D

I believe that two layers of cache are required: the local response cache is used to store tile images downloaded from the web on the local file system. The second layer is the actual tile (image) cache.

As far as I remember the tile map is mostly used for rendering and look-ups, but I could be wrong.

I think you could just put your offline map in the local response cache (and disable the web download) to make it work. Do you hit any obstacles?

**Comment by eialbur** [comment]
I am a retired programmer - haven't programmed for almost two years -
trying to get back into the groove on a personal project. I do lots of
offroading and want to carry my program with me - and frequently I am in a
cell phone dead zone - so having the map available offline is critical for
me.

I am making changes that you probably will not be interested in - but a
couple may be helpful.

I got rid of some of some synchronization by using AtomicBoolean for
Tile.isLoading and Tile.loaded.  I'm not sure Tile.loaded is necessary (can
I just look at the image?), but I'm trying not to fix things that aren't
broken.

I agree with two layers of cache. I broke the tile cache out into a
separate object (I get confused if an object is doing too many different
things).  I considered the comment I read about having a single cache for
all tiles for all factories but decided against it - in order to prevent
mixing tiles from different sites you'd have to partition the cache anyway,
so let's just have a cache per site.

I decided to have the second cache double as the mechanism for me to store
maps offline. I am not familiar with ResponseCache so I just shoved some
file I/O into the retrieveTileImage method - this way I do all image I/O in
the same spot. Pardon the hard-coded cache directory (I am still in
development). I recognize that this may not be the most flexible approach,
but right now it meets my needs and I'm just trying to get my program to
work. I was concerned at first about synchronization issues doing the file
I/O but realized that you've protected the queue so that no tile can be in
it more than once - therefore there can be no contention on the File I/O.

private byte[] retrieveTileImage(URL url, Tile tile)
throws IOException {
InputStream ins;

File tileFile = new File(
"C:\\temp\\tilecache\\" + getInfo().getName(),   // different dir for each
provider
tile.getKey());
boolean tileOnDisk = tileFile.exists();

if (tileOnDisk) {
// System.out.println(tile.getKey() + " disk");
ins = new FileInputStream(tileFile);
} else {
// System.out.println(tile.getKey() + " net");
URLConnection connection = url.openConnection();
connection.setConnectTimeout(5000);  // short timeouts works better in my
environment
connection.setReadTimeout(5000);
connection.setRequestProperty("User-Agent", userAgent);
connection.connect();
ins = connection.getInputStream();
}

ByteArrayOutputStream bout = new ByteArrayOutputStream();
byte[] buf = new byte[1024];   // made buf a little bigger
while (true) {
int n = ins.read(buf);
if (n == -1)
break;
bout.write(buf, 0, n);
}
ins.close();

byte[] data = bout.toByteArray();
bout.close();

if (!tileOnDisk) {
OutputStream fos = new FileOutputStream(tileFile);
fos.write(data);
fos.close();
}

return data;
}


I have now just started working on restricting the map at the application
level. I have put in a min and max zoomLevels for the application (in
addition to the min and max possible for the site). I also want to restrict
panning. I see there is some code which restricts panning, but I don't
think it is going to do it for me. I want to set a Rectangle and never
allow the user to pan (or zoom) outside of that Rectangle.

Thanks for taking the time to respond to me.

**Comment by msteiger** [comment]
Thank you as well. A few remarks: if you're using Java7 or 8, you can use the very useful methods in the Files class to write data to disk.

I also prefer avoiding the ResponseCache, since it also caches other URL requests, independent from the map component.

Most of the code is ancient and better solutions exist today. I tried to find a balance between not breaking existing APIs and improvements with a tendency to the latter. So I'd be happy to get some modern features in.
