### ISSUE TITLE
GeoUtil.getMapBounds

### ISSUE THREAD

**Issue by eialbur** [msteiger/jxmapviewer2#61]
When I call GeoUtil.getMapBounds it looks like it reverses the Lat and Long.

**Comment by eialbur** [comment]
I think it may just be getNorthWest and getSouthEast that has them backwards

**Comment by msteiger** [comment]
Ah ok, will have a look, thanks!

**Comment by msteiger** [comment]
Fixed! Please check that it really solves your problem.
