### ISSUE TITLE
Load custom image not tiled

### ISSUE THREAD

**Issue by respeso** [msteiger/jxmapviewer2#67]
Hello Martin, thank's for this work.
I have worked with this library two years ago, to displayed maps. But now I think, it could be utilized to display a single image with an arbitrary coordinate system and make zoom, move image, etc...
Is it posible to load a custom image not tiled from local file with this library?.
Greetings

**Comment by msteiger** [comment]
Yes, that should work. You can provide a custom `TileFactory`  that just provides a single tile from a local folder. Zooming should work, too. How big is the image you have?
