### ISSUE TITLE
Need help - Thanks

### ISSUE THREAD

**Issue by ivan-marroquin** [msteiger/jxmapviewer2#68]
Hi Martin,

Sorry to report this incident under jxmapviewer2 but I can't find the solution to run the command "gradlew run" for 2D colormap explorer application. I get this error:

> Could not resolve de.fhg.igd:pcolor:1.4.1.
  Required by:
      de.fhg.igd.iva:metrics:2018-07-17-08-07-32
   > Could not GET 'http://artifactory.esdi-humboldt.eu/artifactory/libs-release/de/fhg/igd/pcolor/1.4.1/pcolor-1.4.1.pom'.
      > Connection to http://artifactory.esdi-humboldt.eu refused

It seems that the web address "http://artifactory.esdi-humboldt.eu" is no longer available. 

Do you have other suggestions?

Many thanks,

Ivan

**Comment by msteiger** [comment]
Will answer there.
