### ISSUE TITLE
Cannot add event on waypoint

### ISSUE THREAD

**Issue by samouzou5** [msteiger/jxmapviewer2#70]
Hello, I want to add a focus event to my waypoints in the route (thanks to a JToolTip), to show the city name associated to tehe waypoint but I don't find anything about that in the project. Is it possible to do that?

Thank you

**Comment by msteiger** [comment]
Have a look at this example:
https://github.com/msteiger/jxmapviewer2/blob/master/examples/src/sample7_swingwaypoints/SwingWaypointOverlayPainter.java

It used standard JButton Swing components to manage waypoints. They respond to focus events just like any other JButton. Does that solve your issue?

**Comment by samouzou5** [comment]
Hello, that's not what I want to do. I want a JToolTip on each DefaultWaypoint that I use to show the city associated to the waypoint thanks to the method setTipText(). I don't know if it is possible?

Thank you

**Comment by msteiger** [comment]
If you always want to show the city name, you could implement the SwingWaypointOverlayPainter.doPaint() method to render whatever you like. If you want tooltip-like behavior, you could actually place `JButton` elements at the corresponding location and move them when the map is moved.

**Comment by samouzou5** [comment]
Hello, it's okay for me thank you
