### ISSUE TITLE
Missing mechanism for attribution

### ISSUE THREAD

**Issue by NopMap** [msteiger/jxmapviewer2#71]
The use of OSM maps requires some attribution to be shown on or next to the map.

It is possible to use multiple maps by keeping multiple TileFactory / TileFactoryInfo in an array. But these classes have no support for an attribution text. If you want to show proper attribution, you have to implement this redundantly in parallel.

TileFactoryInfo should have a property String attribution and some support to query this property, maybe via the TileFactory. This way you could control all properties of a map in the same place.

**Comment by msteiger** [comment]
Interesting thought, sorry for the delay. Will investigate over the Easter holidays.

**Comment by msteiger** [comment]
Should be OK now, can you please check?
