### ISSUE TITLE
Example for offline maps

### ISSUE THREAD

**Issue by fubian** [msteiger/jxmapviewer2#72]
May you give me an example hot to use offline map tiles from OSM with JXMapViewer2?

**Comment by msteiger** [comment]
There is no example afaik. Beware that you might need a very large amount of files to cover a reasonable big area with sufficient detail. And they become outdated fairly quickly. Are you sure that you really want pure offline maps?

**Comment by fubian** [comment]
I will run an air-gapped application, so yes I am sure that I want to use pure offline maps!

My current solution is to change the base URL of the TileFactoryInfo:

```
TileFactoryInfo info = new OSMTileFactoryInfo("offline", path_to_tile_directory);
```

Is this a sufficient way?

**Comment by msteiger** [comment]
Can you please check if #76 solves your problem?
