### ISSUE TITLE
Wrong totalMapZoom in OSMTileFactoryInfo

### ISSUE THREAD

**Issue by NopMap** [msteiger/jxmapviewer2#73]
The OSM map has 19 zoom levels (19 being the most detailed)

In OSMTileFactoryInfo totalMapZoom is set to 19.
But in method getTileUrl() zoom is converted: "zoom = 19 - zoom"
With 1 being the most detailed zoom in jxmapviewer2 this means that the highest zoom level is 18.

So totalMapZoom should be 19 to actually use all zoom levels.

**Comment by msteiger** [comment]
I remember this bug. It should have been fixed ages ago. I will dig into it. Thanks for reporting!

**Comment by msteiger** [comment]
Should be fixed in `2.5-SNAPSHOT` .. can you please check?
