### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gastendonk** [msteiger/jxmapviewer2#78]
The java.net links do not work anymore.

SwingX-ws-2009_06_14.jar http://java.net/projects/swingx
SwingX 1.6.3 (released Feb 2012) http://java.net/projects/swingx-ws

https://github.com/msteiger/jxmapviewer2/blob/master/README.md

**Comment by msteiger** [comment]
Yes, that's certainly true, but I don't think that we can do anything about it, can we?

**Comment by gastendonk** [comment]
If there's no new link for it then remove the broken link. ;-)

**Comment by msteiger** [comment]
Fixed in 8cdebff79af78fbdab61abec6f0733436e00c17e
