### ISSUE TITLE
Build with Offline map PR

### ISSUE THREAD

**Issue by kellykelly3** [msteiger/jxmapviewer2#80]
Hi.  I have been using the 2.4 build open zip files of tiles and noticed that when a tile is not found that a FileNotFoundException appears in the log\debug console output.  I see that you have fixed that issue in the [Offline maps example ](https://github.com/msteiger/jxmapviewer2/commit/0f7ba774b528808f07cd479303856db69d148345)PR.  Will there be a new build with that includes that PR soon?  

Thanks,
Kelly

**Comment by msteiger** [comment]
Good point, I will fix it.

**Comment by msteiger** [comment]
Fixed in version 2.5
