### ISSUE TITLE
question: performance good practice

### ISSUE THREAD

**Issue by zprd** [msteiger/jxmapviewer2#85]
Hi, I am playing with the RoutePainter from the samples.

displaying more than 1000 bike stations in town, works ok for waypoints but route painting of more than 1000 route is very slow.

I am new to java2d, do you have any tips to display this amount of routes?

**Comment by msteiger** [comment]
I think that it is usually never a good idea to render 1000 routes in one picture. It will be impossible to see anything. Maybe you can find a good subset of the routes, maybe using filters?

In any case, simpler rendering is faster. If you disable outlines and complex corner connections, it should be a bit faster.
