### ISSUE TITLE
zoomToBestFit: center is incorrectly computed (average of positions)

### ISSUE THREAD

**Issue by laurentpeters** [msteiger/jxmapviewer2#86]
In commit 45add7adf86af63b37c63f61aa6be0873cd593b0, the way the center is computed in zoomToBestFit was modified. Before the change, it was the center of the bounding rectangle of all the positions. After the change it is computed as the average of the positions.

This is not correct. It does not ensure that all the points are visible after zoomToBestFit.

Consider a square containing 11 points. 10 points are positioned on the left edge and 1 point is positioned on the right edge. The center should be the center of the square. But If you consider average of the positions of the points, the computed center will be placed near the left edge and not in the center of the square. With zoomToBestFit, the right point will not be visible.

The average of the positions is therefore not a good solution, it does not ensure that all the points are visible.

**Comment by msteiger** [comment]
You are absolutely right, I assume that it was a mistake. Will have a deeper look asap.

**Comment by msteiger** [comment]
Can you please review the PR?
