### ISSUE TITLE
Beginner question: How to view the examples?

### ISSUE THREAD

**Issue by hvdwolf** [msteiger/jxmapviewer2#92]
I'm sorry to bother you with this, but I tried a lot of things to make this work and I can't make it work.
I'm used to gradle and IntelliJ, so it might probably be my lack of knowledge of maven.

I compiled the examples with a `mvn install` and also tried `mvn package`.
This created a jxmapviewer2-examples-2.5.jar
Simple start does not work as there is no manifest created, so I tried the `java -cp` approach.
I tried a lot of combinatiions like `java -cp jxmapviewer2-examples-2.5.jar sample1_basics.Sample1`  and likewise combinations, but only get errors like "xyz class not found".

Please explain and please put in small readme.md in examples on how to build and how to view the examples.

**Comment by msteiger** [comment]
I think the easiest way would be to open the project in the IDE and run the examples there. Nonetheless, I updated the examples project and the README, so you should be able to run it now as you expect.

**Comment by hvdwolf** [comment]
Thanks for the response, but as you can see from my above post I did exactly as you have now added to the readme
```
$ mvn clean package
$ java -cp target/jxmapviewer2-examples-2.5.jar sample1_basics.Sample1
```
But I get `Error: Could not find or load main class sample1_basics.Sample1`  (and same for the others)

I also loaded it in IntelliJ. Then I get the error `non-managed pom.xml file found` referring to the pom.xml in examples

**Comment by msteiger** [comment]
I guess you need to update your local source code repository to get the latest changes. A simple 
```
$ git pull
```
should do the trick. If you want to open it in IntelliJ you need to open/import it as Maven project.

**Comment by hvdwolf** [comment]
Of course. My stupid mistake.

Yes, it does work now.
Thank you.
