### ISSUE TITLE
ClassLoading optimization

### ISSUE THREAD

**Issue by rjahn** [msteiger/jxmapviewer2#93]
In ProjectProperties, you have:

            ClassLoader classloader = Thread.currentThread().getContextClassLoader();
            is = classloader.getResourceAsStream(PROPERTIES_FILE);
            
But sometimes it happens that, the ClassLoader is a different one....
It would be great to check:

            if (is == null)
            {
            	is = ProjectProperties.class.getResourceAsStream(PROPERTIES_FILE);
            }

**Comment by msteiger** [comment]
Thanks for your report. Does that cause any problems? In what setup?

**Comment by rjahn** [comment]
Yes, sure.

A problem occurs if you have the application class loader A and another class loader B. The application class loader is Thread.currentThread().getContextClassLoader(), but B loads the map viewer. A is the preloaded class loader and B is the dynamic jar class loader.

So if you use the jar in B, it won't work to load the properties file because A doesn't find the resource....

It's not a simple use-case but if you work with different class loaders, this is a problem!

**Comment by msteiger** [comment]
Ah, very interesting. Thanks for the info. I don't have the time right now to look into it. It would be great if you could create a PR for it.

**Comment by msteiger** [comment]
Can you please try https://github.com/msteiger/jxmapviewer2/pull/98 to see if it fixes your issue?

**Comment by rjahn** [comment]
Solves the problem.
