### ISSUE TITLE
Zoom around mouse pointer rather than the center

### ISSUE THREAD

**Issue by rackaracka** [msteiger/jxmapviewer2#94]
I needed to zoom around the mouse position rather than the center of the map. The following code (org.jxmapviewer.JXMapViewer) achieves that (feel free to add it to your nice library if you like it):

	/**
     * Set the current zoom level using the center point of the viewport
     * @param zoom the new zoom level
     */
    public void setZoom(int zoom) {
        Rectangle viewPort = this.getViewportBounds();
        double xPos = viewPort.getWidth() / 2D;
        double yPos = viewPort.getHeight() / 2D;
        this.setZoom(zoom, xPos, yPos);
    }

    /**
     * Sets the zoom level using a position (relative to the viewport) as center point
     * @param zoom new zoom level
     * @param xPos x position
     * @param yPos y position
     */
    public void setZoom(int zoom, double xPos, double yPos)
    {        
        // don't repaint if the zoom has not changed or we are out of the valid zoom levels
        if (zoom == this.getZoom() || this.getTileFactory().getInfo() != null && (zoom < this.getTileFactory().getInfo().getMinimumZoomLevel() || zoom > this.getTileFactory().getInfo().getMaximumZoomLevel()))
        {
            return;
        }

        // keep old value for the event to be fired
        int oldzoom = this.getZoom(); 
        
        // keep the old map size (this is the number of tiles rather than pixels)
        Dimension oldMapSize = getTileFactory().getMapSize(oldzoom);    
         
        // viewport relative position
        Rectangle viewPort = this.getViewportBounds();// need mouse position as absolute value related to map in pixel        
        Point2D oldMousePos = new Point2D.Double(viewPort.getX() + xPos, viewPort.getY() + yPos);
        
        // zoom
        this.zoomLevel = zoom;  
        // and fire event
        this.firePropertyChange("zoom", oldzoom, zoom);
        
        // get the new size
        Dimension newMapSize = getTileFactory().getMapSize(zoom);
        // calculate zoom factor
        double xFactor = newMapSize.getWidth() / oldMapSize.getWidth();
        double yFactor = newMapSize.getHeight() / oldMapSize.getHeight();
        
        // calculate the new "mouse position" using that factor, i.e. x * factor, y * factor
        Point2D newMousePos = new Point2D.Double(oldMousePos.getX() * xFactor, oldMousePos.getY() * yFactor);
        
        // calculate the pixel difference between thos mouse positions
        double xMouseDiff = oldMousePos.getX() - newMousePos.getX();
        double yMouseDiff = oldMousePos.getY() - newMousePos.getY();

        // move the center of the map that difference back
        Point2D oldCenter = getCenter();
        Point2D newCenter = new Point2D.Double(oldCenter.getX() - xMouseDiff, oldCenter.getY() - yMouseDiff);
        
        setCenter(newCenter);         
        repaint();
    }
	
	
The accuracy could be better, the following changes improve it to some degree: 

	public Rectangle getViewportBounds()
    {
        return calculateViewportBounds(getCenter());
    }

    private Rectangle calculateViewportBounds(Point2D centr)
    {
        Insets insets = getInsets();
        // calculate the "visible" viewport area in pixels
        double viewportWidth = getWidth() - insets.left - insets.right;
        double viewportHeight = getHeight() - insets.top - insets.bottom;
        double viewportX = Math.round((centr.getX() -  viewportWidth / 2D));
        double viewportY = Math.round((centr.getY() -  viewportHeight / 2D));
        return new Rectangle((int) Math.round(viewportX), (int) Math.round(viewportY), (int) Math.round(viewportWidth),
                (int) Math.round(viewportHeight));
    }

 	public void setCenter(Point2D center)
    {
        Point2D old = this.getCenter();

        double centerX = center.getX();
        double centerY = center.getY();

        Dimension mapSize = getTileFactory().getMapSize(getZoom());
        double mapHeight =  mapSize.getHeight() * getTileFactory().getTileSize(getZoom());
        double mapWidth =  mapSize.getWidth() * getTileFactory().getTileSize(getZoom());

        if (isRestrictOutsidePanning())
        {
            Insets insets = getInsets();
            double viewportHeight = getHeight() - insets.top - insets.bottom;
            double viewportWidth = getWidth() - insets.left - insets.right;

            // don't let the user pan over the top edge
            Rectangle newVP = calculateViewportBounds(center);
            if (newVP.getY() < 0)
            {
                centerY =   viewportHeight / 2D;
            }

            // don't let the user pan over the left edge
            if (!isHorizontalWrapped() && newVP.getX() < 0)
            {
                centerX =   viewportWidth / 2D;
            }

            // don't let the user pan over the bottom edge
            if (newVP.getY() + newVP.getHeight() > mapHeight)
            {
                centerY =  mapHeight -   viewportHeight / 2D;
            }

            // don't let the user pan over the right edge
            if (!isHorizontalWrapped() && (newVP.getX() + newVP.getWidth() > mapWidth))
            {
                centerX =   mapWidth -  viewportWidth / 2D;
            }

            // if map is to small then just center it vert
            if (mapHeight < newVP.getHeight())
            {
                centerY =  mapHeight / 2D;// viewportHeight/2;// - mapHeight/2;
            }

            // if map is too small then just center it horiz
            if (!isHorizontalWrapped() && mapWidth < newVP.getWidth())
            {
                centerX =  mapWidth / 2D;
            }
        }

        // If center is outside (0, 0,mapWidth, mapHeight)
        // compute modulo to get it back in.
        {
            centerX = centerX % mapWidth;
            centerY = centerY % mapHeight;

            if (centerX < 0)
                centerX += mapWidth;

            if (centerY < 0)
                centerY += mapHeight;
        }

        GeoPosition oldGP = this.getCenterPosition();
        this.center = new Point2D.Double(centerX, centerY);
        firePropertyChange("center", old, this.center);
        firePropertyChange("centerPosition", oldGP, this.getCenterPosition());
        repaint();
    }

**Comment by msteiger** [comment]
Thanks for the report. So you suggest replacing the snippet from the top that you found in the source code with the snippet at the bottom to improve the accuracy? Can you maybe create a PR for your change and explain it a bit? That would be great.

**Comment by rackaracka** [comment]
OK, here is some explanation:

public void setZoom(int zoom) - This is the existing implementation, the body has changed so that it now uses the overloaded method (to avoid code repetitions)

public void setZoom(int zoom, double xPos, double yPos) - This is the overloaded zoom implementation that uses an arbitrary position rather than the map center 

The following methods used a mixture of int and double variables, where the int values caused some precision loss. I've simply changed all int variables to double; functionally they are equivalent:

public Rectangle getViewportBounds()
private Rectangle calculateViewportBounds(Point2D centr)
public void setCenter(Point2D center)

There seems still to be some rounding error somewhere; zooming in and out around the same point multiple times makes the point wandering off a bit. I can live with it, it's not too bad but some picky souls may have an issue with it.

Unfortunately I can't access github from work as it is blocked, therefore adding the code just as a comment.

**Comment by msteiger** [comment]
Thanks for your input. I think the implementation with `ZoomMouseWheelListenerCursor` is OK and does not suffer from rounding errors, so I would leave it as it is, tbh.
