### ISSUE TITLE
Possible race condition in FileBasedLocalCache

### ISSUE THREAD

**Issue by kkieffer** [msteiger/jxmapviewer2#96]
In the get() method of FileBasedLocalCache, the method first checks to see if the file exists, if it does, potentially checks for an update, and then returns an input stream for the file.  I have a thread that periodically cleans old files to keep the cache from growing too large.  If I delete the file between the check for file exists and the opening of the input stream, the stream will fail with FileNotFound exception, and cause the Tile to be marked loading-failed.  

A potential fix is to wrap the `new FileInputStream()` call in a try/catch for FileNotFoundException and return null to indicate the file is not in the cache.

**Comment by msteiger** [comment]
Good point! Can you create a PR for that?
