### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kkieffer** [msteiger/jxmapviewer2#99]
Could we get a 2.6 release that pulls in all the latest changes over this past year?  Much appreciated

**Comment by msteiger** [comment]
Sure, haven't forgotten about it, will do it asap.

**Comment by msteiger** [comment]
Version 2.6 should be available now. Can you please check if everything is as expected?

**Comment by kkieffer** [comment]
All is working as expected however I found another bug - will submit new issue...
